GEMINI_API_KEY = "AIzaSyB0-GW3FrlVDExlahSz7PEUUtv-3a1ESCM"
SUPABASE_URL = "https://roixjrfytzvzogydpxjk.supabase.co"  
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvaXhqcmZ5dHp2em9neWRweGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkzNDAxMDksImV4cCI6MjA5NDkxNjEwOX0.ZReG7lYczVwKqA4zibhQwP4jiP4DWWvtoYqqy28aD0s"